export const componentNames = [
  // Actions
  'VxButton',
  'VxIconButton',
  'VxButtonGroup',
  'VxLink',
  'VxTooltip',
  'VxMoreMenu',

  // Inputs
  'VxCheckbox',
  'VxRadioGroup',
  'VxRadioItem',
  'VxSwitch',
  'VxInput',
  'VxTextarea',
  'VxFormField',
  'VxMaskedInput',
  'VxFileInput',

  // Layout
  'VxCard',
  'VxSeparator',
  'VxAppShell',
  'VxGrid',
  'VxHStack',
  'VxVStack',
  'VxSidebar',
  'VxSidebarItem',
  'VxSidebarItemGroup',
  'VxSidebarSection',
  'VxSidebarHeading',
  'VxSidebarCollapseButton',
  'VxToolbar',
  'VxToolbarButton',
  'VxToolbarLink',
  'VxToolbarSeparator',
  'VxToolbarToggleGroup',
  'VxToolbarToggleItem',

  // Overlays
  'VxDropdownMenu',
  'VxDrawer',
  'VxAvatar',
  'VxDialog',
  'VxClickableCard',

  // Data display
  'VxBadge',
  'VxTabs',
  'VxTabsList',
  'VxTabsTrigger',
  'VxTabsContent',
  'VxAccordion',
  'VxAccordionItem',
  'VxAccordionHeader',
  'VxAccordionTrigger',
  'VxAccordionContent',
  'VxList',
  'VxListItem',
  'VxText',
  'VxLabel',
  'VxSlider',
  'VxToggle',
  'VxToggleGroup',
  'VxToggleGroupItem',
  'VxPinInput',
  'VxNumberField',
  'VxIcon',
  'VxLoading',
  'VxSelect',
  'VxCombobox',
  'VxListbox',
  'VxEditable',
  'VxTagsInput',
  'VxRating',
  'VxCollapsible',
  'VxPopover',
  'VxHoverCard',
  'VxAlertDialog',
  'VxToast',
  'VxToastProvider',
  'VxProgress',
  'VxScrollArea',
  'VxSkeleton',
  'VxAspectRatio',
  'VxSplitterGroup',
  'VxSplitterPanel',
  'VxSplitterResizeHandle',
  'VxStepper',
  'VxStepperItem',
  'VxPagination',
  'VxContextMenu',
  'VxMenubar',
  'VxNavigationMenu',
  'VxNavigationMenuList',
  'VxNavigationMenuItem',
  'VxNavigationMenuTrigger',
  'VxNavigationMenuContent',
  'VxNavigationMenuLink',
  'VxNavigationMenuSection',
  'VxBreadcrumb',
  'VxBreadcrumbItem',
  'VxTopNav',
  'VxTopNavItem',
  'VxTopNavHeading',
  'VxMobileNav',
  'VxMobileNavToggle',
  'VxTree',

  // Picker
  'VxColorArea',
  'VxColorField',
  'VxColorSlider',
  'VxColorSwatch',
  'VxColorSwatchPicker',
  'VxCalendar',
  'VxRangeCalendar',
  'VxMonthPicker',
  'VxMonthRangePicker',
  'VxYearPicker',
  'VxYearRangePicker',
  'VxDatePicker',
  'VxDateRangePicker',

  // Patterns
  'VxPageHeader',
  'VxEmptyState',
  'VxDataTable',
  'VxDataTableServer',
  'VxAttributePresenter',

  // Feedback
  'VxBanner',
  'VxBannerProvider',

  // Utilities
  'VxVisuallyHidden',
] as const
